#!/bin/sh
# Build a libJudy install prefix (include/Judy.h + lib/libJudy.a) from
# pristine Judy-1.0.5 sources, with caller-controlled CFLAGS.
#
#   build-stock.sh <judy-src-dir> <out-prefix> [CFLAGS...]
#
# <judy-src-dir> is upstream's src/ directory — e.g. this repo's byte-
# identical import at libjudy/src (tarball sha256
# d2704089f85fdb6f2cd7e77be21170ced4b4375c03ef1ad4cf1075bd414a63eb).
# The source dir is only read, never written: generated tables and objects
# go under <out-prefix>/obj.
#
# This replicates upstream src/obj/Makefile.am's scheme — each JudyCommon
# translation unit compiled once per variant with -DJUDY1 / -DJUDYL, the
# JudyGet/JudyPrevNext(Empty) units compiled per direction, and the
# Judy1Tables.c/JudyLTables.c units generated by running JudyTables.c.
# It exists so the differential harness can be validated against stock
# sources at chosen optimization / sanitizer flags without autotools
# (the 2007 config.guess predates aarch64) and without network access.
#
# -std=gnu99: 1.0.5 is K&R-era C that no longer compiles under gcc>=14
# defaults (C23). Stock sources warn copiously and warnings are deliberately
# NOT suppressed: at -O3, gcc's -Waggressive-loop-optimizations warning at
# Judy1Set.c is the compiler announcing the very UB it exploits (#131), and
# the validation log wants that line. Redirect stderr if the noise matters.
set -eu

SRC=$1
OUT=$2
shift 2
CFLAGS=${*:-"-O2"}
CC=${CC:-cc}

[ -f "$SRC/Judy.h" ] || { echo "no Judy.h under $SRC" >&2; exit 2; }

mkdir -p "$OUT/obj" "$OUT/lib" "$OUT/include"
cd "$OUT/obj"

COMMON="-std=gnu99 -DJU_64BIT $CFLAGS -I$SRC -I$SRC/JudyCommon"
INC1="-I$SRC/Judy1"
INCL="-I$SRC/JudyL"

# shellcheck disable=SC2086
c1() { $CC $COMMON $INC1 -DJUDY1 "$@"; }
# shellcheck disable=SC2086
cl() { $CC $COMMON $INCL -DJUDYL "$@"; }

# Generated tables: JudyTables.c is a generator program that writes
# Judy1Tables.c / JudyLTables.c into the current directory.
c1 "$SRC/JudyCommon/JudyTables.c" -o gen1 && ./gen1
cl "$SRC/JudyCommon/JudyTables.c" -o genL && ./genL
c1 -c Judy1Tables.c -o Judy1Tables.o
cl -c JudyLTables.c -o JudyLTables.o

for f in JudyByCount JudyCascade JudyCount JudyCreateBranch JudyDecascade \
         JudyDel JudyFirst JudyFreeArray JudyIns JudyInsArray \
         JudyInsertBranch JudyMallocIF JudyMemActive JudyMemUsed; do
    c1 -c "$SRC/JudyCommon/$f.c" -o "1_$f.o"
    cl -c "$SRC/JudyCommon/$f.c" -o "L_$f.o"
done

c1 -c "$SRC/JudyCommon/JudyGet.c" -o 1_JudyGet.o
c1 -DJUDYGETINLINE -c "$SRC/JudyCommon/JudyGet.c" -o 1_JudyGetInline.o
cl -c "$SRC/JudyCommon/JudyGet.c" -o L_JudyGet.o
cl -DJUDYGETINLINE -c "$SRC/JudyCommon/JudyGet.c" -o L_JudyGetInline.o

for dir in NEXT PREV; do
    c1 -DJUDY$dir -c "$SRC/JudyCommon/JudyPrevNext.c" -o "1_$dir.o"
    cl -DJUDY$dir -c "$SRC/JudyCommon/JudyPrevNext.c" -o "L_$dir.o"
    c1 -DJUDY$dir -c "$SRC/JudyCommon/JudyPrevNextEmpty.c" -o "1_${dir}Empty.o"
    cl -DJUDY$dir -c "$SRC/JudyCommon/JudyPrevNextEmpty.c" -o "L_${dir}Empty.o"
done

# shellcheck disable=SC2086
$CC $COMMON -c "$SRC/JudyCommon/JudyMalloc.c" -o JudyMalloc.o
# shellcheck disable=SC2086
$CC $COMMON -c "$SRC/JudySL/JudySL.c" -o JudySL.o
# shellcheck disable=SC2086
$CC $COMMON -c "$SRC/JudyHS/JudyHS.c" -o JudyHS.o

rm -f "$OUT/lib/libJudy.a"
ar rcs "$OUT/lib/libJudy.a" ./*.o
cp "$SRC/Judy.h" "$OUT/include/"
echo "built $OUT/lib/libJudy.a  (CFLAGS: $CFLAGS)"
